/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo.proto */

#ifndef PROTOBUF_C_demo_2eproto__INCLUDED
#define PROTOBUF_C_demo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _People__Person People__Person;
typedef struct _People__Person__PhoneNumber People__Person__PhoneNumber;


/* --- enums --- */

typedef enum _People__Person__Gender {
  PEOPLE__PERSON__GENDER__FEMALE = 0,
  PEOPLE__PERSON__GENDER__MALE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PEOPLE__PERSON__GENDER)
} People__Person__Gender;
typedef enum _People__Person__PhoneType {
  PEOPLE__PERSON__PHONE_TYPE__MOBILE = 0,
  PEOPLE__PERSON__PHONE_TYPE__HOME = 1,
  PEOPLE__PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PEOPLE__PERSON__PHONE_TYPE)
} People__Person__PhoneType;

/* --- messages --- */

struct  _People__Person__PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  People__Person__PhoneType type;
};
#define PEOPLE__PERSON__PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&people__person__phone_number__descriptor) \
    , (char *)protobuf_c_empty_string, PEOPLE__PERSON__PHONE_TYPE__MOBILE }


struct  _People__Person
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  People__Person__Gender gender;
  /*
   *动态数组，构成元素的数据类型是上面定义的PhoneNumber
   */
  size_t n_phones;
  People__Person__PhoneNumber **phones;
};
#define PEOPLE__PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&people__person__descriptor) \
    , (char *)protobuf_c_empty_string, 0, PEOPLE__PERSON__GENDER__FEMALE, 0,NULL }


/* People__Person__PhoneNumber methods */
void   people__person__phone_number__init
                     (People__Person__PhoneNumber         *message);
/* People__Person methods */
void   people__person__init
                     (People__Person         *message);
size_t people__person__get_packed_size
                     (const People__Person   *message);
size_t people__person__pack
                     (const People__Person   *message,
                      uint8_t             *out);
size_t people__person__pack_to_buffer
                     (const People__Person   *message,
                      ProtobufCBuffer     *buffer);
People__Person *
       people__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   people__person__free_unpacked
                     (People__Person *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*People__Person__PhoneNumber_Closure)
                 (const People__Person__PhoneNumber *message,
                  void *closure_data);
typedef void (*People__Person_Closure)
                 (const People__Person *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor people__person__descriptor;
extern const ProtobufCMessageDescriptor people__person__phone_number__descriptor;
extern const ProtobufCEnumDescriptor    people__person__gender__descriptor;
extern const ProtobufCEnumDescriptor    people__person__phone_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_demo_2eproto__INCLUDED */
