/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo.pb-c.h"
void   people__person__phone_number__init
                     (People__Person__PhoneNumber         *message)
{
  static const People__Person__PhoneNumber init_value = PEOPLE__PERSON__PHONE_NUMBER__INIT;
  *message = init_value;
}
void   people__person__init
                     (People__Person         *message)
{
  static const People__Person init_value = PEOPLE__PERSON__INIT;
  *message = init_value;
}
size_t people__person__get_packed_size
                     (const People__Person *message)
{
  assert(message->base.descriptor == &people__person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t people__person__pack
                     (const People__Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &people__person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t people__person__pack_to_buffer
                     (const People__Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &people__person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
People__Person *
       people__person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (People__Person *)
     protobuf_c_message_unpack (&people__person__descriptor,
                                allocator, len, data);
}
void   people__person__free_unpacked
                     (People__Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &people__person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor people__person__phone_number__field_descriptors[2] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(People__Person__PhoneNumber, number),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(People__Person__PhoneNumber, type),
    &people__person__phone_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned people__person__phone_number__field_indices_by_name[] = {
  0,   /* field[0] = number */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange people__person__phone_number__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor people__person__phone_number__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "people.Person.PhoneNumber",
  "PhoneNumber",
  "People__Person__PhoneNumber",
  "people",
  sizeof(People__Person__PhoneNumber),
  2,
  people__person__phone_number__field_descriptors,
  people__person__phone_number__field_indices_by_name,
  1,  people__person__phone_number__number_ranges,
  (ProtobufCMessageInit) people__person__phone_number__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue people__person__gender__enum_values_by_number[2] =
{
  { "FEMALE", "PEOPLE__PERSON__GENDER__FEMALE", 0 },
  { "MALE", "PEOPLE__PERSON__GENDER__MALE", 1 },
};
static const ProtobufCIntRange people__person__gender__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex people__person__gender__enum_values_by_name[2] =
{
  { "FEMALE", 0 },
  { "MALE", 1 },
};
const ProtobufCEnumDescriptor people__person__gender__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "people.Person.Gender",
  "Gender",
  "People__Person__Gender",
  "people",
  2,
  people__person__gender__enum_values_by_number,
  2,
  people__person__gender__enum_values_by_name,
  1,
  people__person__gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue people__person__phone_type__enum_values_by_number[3] =
{
  { "MOBILE", "PEOPLE__PERSON__PHONE_TYPE__MOBILE", 0 },
  { "HOME", "PEOPLE__PERSON__PHONE_TYPE__HOME", 1 },
  { "WORK", "PEOPLE__PERSON__PHONE_TYPE__WORK", 2 },
};
static const ProtobufCIntRange people__person__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex people__person__phone_type__enum_values_by_name[3] =
{
  { "HOME", 1 },
  { "MOBILE", 0 },
  { "WORK", 2 },
};
const ProtobufCEnumDescriptor people__person__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "people.Person.PhoneType",
  "PhoneType",
  "People__Person__PhoneType",
  "people",
  3,
  people__person__phone_type__enum_values_by_number,
  3,
  people__person__phone_type__enum_values_by_name,
  1,
  people__person__phone_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor people__person__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(People__Person, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(People__Person, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(People__Person, gender),
    &people__person__gender__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phones",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(People__Person, n_phones),
    offsetof(People__Person, phones),
    &people__person__phone_number__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned people__person__field_indices_by_name[] = {
  2,   /* field[2] = gender */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  3,   /* field[3] = phones */
};
static const ProtobufCIntRange people__person__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor people__person__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "people.Person",
  "Person",
  "People__Person",
  "people",
  sizeof(People__Person),
  4,
  people__person__field_descriptors,
  people__person__field_indices_by_name,
  1,  people__person__number_ranges,
  (ProtobufCMessageInit) people__person__init,
  NULL,NULL,NULL    /* reserved[123] */
};
